## Importing Libraries

In [2]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

import pytz
from datetime import datetime

In [3]:
# IST Time Function
def get_ist_hour():
    india_tz = pytz.timezone("Asia/Kolkata")
    current_time = datetime.now(india_tz)
    return current_time.hour

In [4]:
# Time Visibility Function
def is_time_between(start_hour, end_hour):
    current_hour = get_ist_hour()
    return start_hour <= current_hour < end_hour

In [5]:
# Google's Color Palette
GOOGLE_COLORS = {
    "blue": "#4285F4",
    "green": "#34A853",
    "yellow": "#FBBC05",
    "red": "#EA4335"
}

### Task-1: Grouped Bar Chart

In [6]:
t1_df = pd.read_csv("../Data/Task_wise_dataset/task1_grouped.csv")

t1_df

           Category    Rating  Reviews   Installs
0            SPORTS  4.400000  1988557  120621000
1              GAME  4.342857  2209062  108691000
2            FAMILY  4.432558  3056570  108595820
3             TOOLS  4.285714   331560   72010000
4   PERSONALIZATION  4.475000   155996   15060000
5      PRODUCTIVITY  4.440000   221779   11610000
6     COMMUNICATION  4.300000   367412   11501000
7     ENTERTAINMENT  4.350000   745832   11000000
8       PHOTOGRAPHY  4.300000   542561   10000000
9  TRAVEL_AND_LOCAL  4.100000      974    1001000

In [7]:
t1_df.shape

(10, 4)

In [16]:
# Group Bar Chart
fig = make_subplots(
    specs=[[{"secondary_y": True}]]
)

# Avg Rating Bar
fig.add_trace(
    go.Bar(
        x=t1_df["Category"],
        y=t1_df["Rating"],
        name="Average Rating",
        marker_color=GOOGLE_COLORS["yellow"],
        hovertemplate="<b>Category:</b> %{x}<br>" + "<b>Average Rating:</b> %{y:.2f}<extra></extra>",
        offsetgroup=1,
        width=0.35
    ),
    secondary_y=False
)

# Total Review Bar
fig.add_trace(
    go.Bar(
        x=t1_df["Category"],
        y=t1_df["Reviews"],
        name="Total Reviews",
        marker_color=GOOGLE_COLORS["blue"],
        hovertemplate="<b>Category:</b> %{x}<br>" + "<b>Total Reviews:</b> %{y:,}<extra></extra>",
        offsetgroup=2,
        width=0.35
    ),
    secondary_y=True
)

In [17]:
# Update Layout
fig.update_layout(

    title={
        "text":"Top 10 App Categories: Average Rating vs Total Reviews",
        "x": 0.5
    },

    template="plotly_white",
    barmode="group",
    height=650,
    width=1200,
    legend_title="Metrics",
)

In [18]:
# Improving Axis & Hover Style

# X-axis
fig.update_xaxes(
    title_text="Category",
    tickangle=-30
)

# Left Y-axis
fig.update_yaxes(
    title_text="Average Rating",
    secondary_y=False
)

# Right Y-axis
fig.update_yaxes(
    title_text="Total Reviews",
    separatethousands=True,
    secondary_y=True
)

In [20]:
fig.show(renderer="browser")

### Task-2: Choropleth Map

In [79]:
t2_df = pd.read_csv("../Data/Task_wise_dataset/task2_grouped.csv")
t2_df

        Category    Installs
0          TOOLS  7875000000
1         FAMILY  5875000000
2   PRODUCTIVITY  5725000000
3    PHOTOGRAPHY  4590000000
4  VIDEO_PLAYERS  3895000000

In [80]:
# Dummy Countries
t2_df["Country"] = [
    "United States",
    "Russia",          
    "Brazil",  
    "India",          
    "Canada"  
]

In [81]:
# Highlight Columns
t2_df["Highlight"] = np.where(
    t2_df["Installs"] > 1_000_000,
    "High Install",
    "Normal"
)

In [82]:
t2_df

        Category    Installs        Country     Highlight
0          TOOLS  7875000000  United States  High Install
1         FAMILY  5875000000         Russia  High Install
2   PRODUCTIVITY  5725000000         Brazil  High Install
3    PHOTOGRAPHY  4590000000          India  High Install
4  VIDEO_PLAYERS  3895000000         Canada  High Install

In [83]:
# Choropleth Map
fig = px.choropleth(
    t2_df,
    locations="Country",
    locationmode="country names",
    color="Installs",
    hover_name="Category",
    hover_data={
        "Installs": ":,",
        "Highlight": True
    },
    color_continuous_scale=[
        GOOGLE_COLORS["blue"],
        GOOGLE_COLORS["green"],
        GOOGLE_COLORS["yellow"],
        GOOGLE_COLORS["red"]
    ],
    title=
    "Global Installs by App Category"
)

C:\Users\Om\AppData\Local\Temp\ipykernel_28716\2812728371.py:2: DeprecationWarning: The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.
  fig = px.choropleth(

In [84]:
# Hover & Layout
fig.update_traces(
    hovertemplate=
    "<b>Country:</b> %{location}<br>" +
    "<b>Category:</b> %{hovertext}<br>" +
    "<b>Total Installs:</b> %{z:,}<br>" +
    "<b>Status:</b> %{customdata[1]}<extra></extra>"
)

In [85]:
# Layout Styling
fig.update_layout(
    template="plotly_white",
    height=650,
    width=1200,
    title={
        "x": 0.5
    },
    geo=dict(
        showframe=False,
        showcoastlines=True,
        projection_type="equirectangular"
    ),
    coloraxis_colorbar=dict(
        title="Installs"
    )
)

In [86]:
fig.show(renderer="browser")