## Importing Libraries

In [1]:
import numpy as np
import pandas as pd

## Importing Datasets

In [2]:
# Merging the two datasets
app_df = pd.read_csv('..//Data//Cleaned_Data//cleaned_app_data.csv')
review_df = pd.read_csv('..//Data//Cleaned_Data//cleaned_review_data.csv')

In [3]:
print(app_df.head())
print(review_df.head())

                                 App          Category  Rating  Reviews  \
0             GollerCepte Live Score            SPORTS     4.2     9992
1       Ad Block REMOVER - NEED ROOT             TOOLS     3.3      999
2                SnipSnap Coupon App          SHOPPING     4.2     9975
3  US Open Tennis Championships 2018            SPORTS     4.0     9971
4                         DreamTrips  TRAVEL_AND_LOCAL     4.7     9971

        Size  Installs  Type  Price Content Rating          Genres  \
0  31.000000   1000000  Free    0.0       Everyone          Sports
1   0.088867    100000  Free    0.0       Everyone           Tools
2  18.000000   1000000  Free    0.0       Everyone        Shopping
3  33.000000   1000000  Free    0.0       Everyone          Sports
4  22.000000    500000  Free    0.0           Teen  Travel & Local

  Last Updated Current Ver Android Ver  Updated_Month  Updated_Year
0   2018-05-23         6.5  4.1 and up              5          2018
1   2013-12-17         3.2  2.2 and up             12          2013
2   2018-01-22         1.4  4.3 and up              1          2018
3   2018-06-05         7.1  5.0 and up              6          2018
4   2018-08-06      1.28.1  5.0 and up              8          2018
                     App                                  Translated_Review  \
0  10 Best Foods for You  I like eat delicious food. That's I'm cooking ...
1  10 Best Foods for You    This help eating healthy exercise regular basis
2  10 Best Foods for You         Works great especially going grocery store
3  10 Best Foods for You                                       Best idea us
4  10 Best Foods for You                                           Best way

  Sentiment  Sentiment_Polarity  Sentiment_Subjectivity  Review_length  \
0  Positive                1.00                0.533333            122
1  Positive                0.25                0.288462             47
2  Positive                0.40                0.875000             42
3  Positive                1.00                0.300000             12
4  Positive                1.00                0.300000              8

   Word_count  Sentiment_Label Subjectivity_Category Polarity_Type
0          21                1                Medium       Neutral
1           7                1                   Low       Neutral
2           6                1                  High       Neutral
3           3                1                Medium       Neutral
4           2                1                Medium       Neutral

## Merging Full Dataset (Contains Multiple row of Same App)

In [ ]:
# performing a left join to merge the datasets on the App column
merged_df = pd.merge(app_df, review_df, on='App', how='left')

In [ ]:
# validating the merged dataset
print(merged_df.shape)
merged_df.head()

(35624, 24)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,...,Updated_Year,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity,Review_length,Word_count,Sentiment_Label,Subjectivity_Category,Polarity_Type
0,GollerCepte Live Score,SPORTS,4.2,9992,31.000000,1000000,Free,0.0,Everyone,Sports,...,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ad Block REMOVER - NEED ROOT,TOOLS,3.3,999,0.088867,100000,Free,0.0,Everyone,Tools,...,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SnipSnap Coupon App,SHOPPING,4.2,9975,18.000000,1000000,Free,0.0,Everyone,Shopping,...,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,US Open Tennis Championships 2018,SPORTS,4.0,9971,33.000000,1000000,Free,0.0,Everyone,Sports,...,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DreamTrips,TRAVEL_AND_LOCAL,4.7,9971,22.000000,500000,Free,0.0,Teen,Travel & Local,...,2018,I'm grateful booking engine dreamtrips. I've a...,Positive,0.2,0.2,150.0,21.0,1.0,Low,Neutral

In [7]:
merged_df.to_csv('..\\Data\\Cleaned_Data\\merged_dataset.csv', index=False)

## Aggregated Dataset (Contains one row per each app)

In [9]:
review_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29692 entries, 0 to 29691
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     29692 non-null  str
 1   Translated_Review       29692 non-null  str
 2   Sentiment               29692 non-null  str
 3   Sentiment_Polarity      29692 non-null  float64
 4   Sentiment_Subjectivity  29692 non-null  float64
 5   Review_length           29692 non-null  int64
 6   Word_count              29692 non-null  int64
 7   Sentiment_Label         29692 non-null  int64
 8   Subjectivity_Category   29692 non-null  str
 9   Polarity_Type           29692 non-null  str
dtypes: float64(2), int64(3), str(5)
memory usage: 6.5 MB

In [10]:
# Group Review Dataset
review_agg = review_df.groupby("App").agg({
    "Sentiment_Polarity": "mean",
    "Sentiment_Subjectivity": "mean",
    "Translated_Review": "count",
    "Review_length": "mean",
    "Word_count": "mean"
}).reset_index()

In [11]:
# renaming columns for clarity
review_agg = review_agg.rename(columns={
    "Translated_Review": "Total_Reviews",
    "Sentiment_Polarity": "Avg_Sentiment_Polarity",
    "Sentiment_Subjectivity": "Avg_Sentiment_Subjectivity",
    "Review_length": "Avg_Review_Length",
    "Word_count": "Avg_Word_Count"
})

In [12]:
review_agg.head()

,App,Avg_Sentiment_Polarity,Avg_Sentiment_Subjectivity,Total_Reviews,Avg_Review_Length,Avg_Word_Count
0,10 Best Foods for You,0.465906,0.493254,95,39.936842,6.778947
1,104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室,0.358227,0.508907,36,40.861111,6.861111
2,11st,0.185943,0.455340,39,68.384615,12.487179
3,1800 Contacts - Lens Store,0.318145,0.591098,40,60.375000,9.250000
4,1LINE – One Line with One Touch,0.196290,0.557315,38,22.868421,3.947368

In [13]:
# Merging Aggregated Review Data with App Data
aggre_df = pd.merge(app_df, review_agg, on='App', how='left')

In [14]:
print(aggre_df.shape)
aggre_df.head()

(8190, 20)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Updated_Month,Updated_Year,Avg_Sentiment_Polarity,Avg_Sentiment_Subjectivity,Total_Reviews,Avg_Review_Length,Avg_Word_Count
0,GollerCepte Live Score,SPORTS,4.2,9992,31.000000,1000000,Free,0.0,Everyone,Sports,2018-05-23,6.5,4.1 and up,5,2018,NaN,NaN,NaN,NaN,NaN
1,Ad Block REMOVER - NEED ROOT,TOOLS,3.3,999,0.088867,100000,Free,0.0,Everyone,Tools,2013-12-17,3.2,2.2 and up,12,2013,NaN,NaN,NaN,NaN,NaN
2,SnipSnap Coupon App,SHOPPING,4.2,9975,18.000000,1000000,Free,0.0,Everyone,Shopping,2018-01-22,1.4,4.3 and up,1,2018,NaN,NaN,NaN,NaN,NaN
3,US Open Tennis Championships 2018,SPORTS,4.0,9971,33.000000,1000000,Free,0.0,Everyone,Sports,2018-06-05,7.1,5.0 and up,6,2018,NaN,NaN,NaN,NaN,NaN
4,DreamTrips,TRAVEL_AND_LOCAL,4.7,9971,22.000000,500000,Free,0.0,Teen,Travel & Local,2018-08-06,1.28.1,5.0 and up,8,2018,0.371277,0.438569,34.0,71.088235,10.941176

In [15]:
# Validating the changes made to the dataset
print(aggre_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 8190 entries, 0 to 8189
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   App                         8190 non-null   str
 1   Category                    8190 non-null   str
 2   Rating                      8190 non-null   float64
 3   Reviews                     8190 non-null   int64
 4   Size                        8190 non-null   float64
 5   Installs                    8190 non-null   int64
 6   Type                        8190 non-null   str
 7   Price                       8190 non-null   float64
 8   Content Rating              8190 non-null   str
 9   Genres                      8190 non-null   str
 10  Last Updated                8190 non-null   str
 11  Current Ver                 8190 non-null   str
 12  Android Ver                 8190 non-null   str
 13  Updated_Month               8190 non-null   int64
 14  Updated_Year                8190 non-null   int64
 15  Avg_Sentiment_Polarity      816 non-null    float64
 16  Avg_Sentiment_Subjectivity  816 non-null    float64
 17  Total_Reviews               816 non-null    float64
 18  Avg_Review_Length           816 non-null    float64
 19  Avg_Word_Count              816 non-null    float64
dtypes: float64(8), int64(4), str(8)
memory usage: 1.9 MB
None

In [16]:
aggre_df.isna().sum()

App                              0
Category                         0
Rating                           0
Reviews                          0
Size                             0
Installs                         0
Type                             0
Price                            0
Content Rating                   0
Genres                           0
Last Updated                     0
Current Ver                      0
Android Ver                      0
Updated_Month                    0
Updated_Year                     0
Avg_Sentiment_Polarity        7374
Avg_Sentiment_Subjectivity    7374
Total_Reviews                 7374
Avg_Review_Length             7374
Avg_Word_Count                7374
dtype: int64

In [17]:
review_cols = [
    "Avg_Sentiment_Polarity",
    "Avg_Sentiment_Subjectivity",
    "Total_Reviews",
    "Avg_Review_Length",
    "Avg_Word_Count"
]

aggre_df[review_cols] = aggre_df[review_cols].fillna(0)

In [18]:
aggre_df["Revenue"] = (aggre_df["Installs"] * aggre_df["Price"])

In [19]:
aggre_df.isna().sum()

App                           0
Category                      0
Rating                        0
Reviews                       0
Size                          0
Installs                      0
Type                          0
Price                         0
Content Rating                0
Genres                        0
Last Updated                  0
Current Ver                   0
Android Ver                   0
Updated_Month                 0
Updated_Year                  0
Avg_Sentiment_Polarity        0
Avg_Sentiment_Subjectivity    0
Total_Reviews                 0
Avg_Review_Length             0
Avg_Word_Count                0
Revenue                       0
dtype: int64

In [20]:
aggre_df.shape

(8190, 21)

In [21]:
aggre_df.to_csv('..\\Data\\Cleaned_Data\\aggregated_merged_dataset.csv', index=False)