In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pytz
import re

In [2]:
app_data = pd.read_csv('..//Data//Cleaned_Data//eda_prepared_dataset.csv')
app_data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,...,Updated_Year,Avg_Sentiment_Polarity,Avg_Sentiment_Subjectivity,Total_Reviews,Avg_Review_Length,Avg_Word_Count,Revenue,Update_Month_Name,Update_Year,Year_Month
0,GollerCepte Live Score,SPORTS,4.2,9992,31.000000,1000000,Free,0.0,Everyone,Sports,...,2018,0.000000,0.000000,0.0,0.000000,0.000000,0.0,May,2018,2018-05
1,Ad Block REMOVER - NEED ROOT,TOOLS,3.3,999,0.088867,100000,Free,0.0,Everyone,Tools,...,2013,0.000000,0.000000,0.0,0.000000,0.000000,0.0,December,2013,2013-12
2,SnipSnap Coupon App,SHOPPING,4.2,9975,18.000000,1000000,Free,0.0,Everyone,Shopping,...,2018,0.000000,0.000000,0.0,0.000000,0.000000,0.0,January,2018,2018-01
3,US Open Tennis Championships 2018,SPORTS,4.0,9971,33.000000,1000000,Free,0.0,Everyone,Sports,...,2018,0.000000,0.000000,0.0,0.000000,0.000000,0.0,June,2018,2018-06
4,DreamTrips,TRAVEL_AND_LOCAL,4.7,9971,22.000000,500000,Free,0.0,Teen,Travel & Local,...,2018,0.371277,0.438569,34.0,71.088235,10.941176,0.0,August,2018,2018-08

In [3]:
review_data = pd.read_csv('..//Data//Cleaned_Data//review_sentiment_eda_dataset.csv')
review_data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,...,Updated_Year,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity,Review_length,Word_count,Sentiment_Label,Subjectivity_Category,Polarity_Type
0,DreamTrips,TRAVEL_AND_LOCAL,4.7,9971,22.0,500000,Free,0.0,Teen,Travel & Local,...,2018,I'm grateful booking engine dreamtrips. I've a...,Positive,0.2000,0.2000,150.0,21.0,1.0,Low,Neutral
1,DreamTrips,TRAVEL_AND_LOCAL,4.7,9971,22.0,500000,Free,0.0,Teen,Travel & Local,...,2018,"This great app. I One book plane, hotel, dream...",Positive,0.8500,0.8750,125.0,20.0,1.0,High,Neutral
2,DreamTrips,TRAVEL_AND_LOCAL,4.7,9971,22.0,500000,Free,0.0,Teen,Travel & Local,...,2018,Its slow rovia keeps going back disappointed g...,Negative,-0.1375,0.4125,58.0,10.0,0.0,Medium,Positive
3,DreamTrips,TRAVEL_AND_LOCAL,4.7,9971,22.0,500000,Free,0.0,Teen,Travel & Local,...,2018,Try get dreams trips Germany UK,Neutral,0.0000,0.0000,31.0,6.0,-1.0,Low,Neutral
4,DreamTrips,TRAVEL_AND_LOCAL,4.7,9971,22.0,500000,Free,0.0,Teen,Travel & Local,...,2018,I cant open travelbook samsung handphone,Neutral,0.0000,0.5000,40.0,6.0,-1.0,Medium,Neutral

## Helper Functions

### IST Time Visibility Functions

In [4]:
# IST time function
def get_ist_hour():

    india_tz = pytz.timezone("Asia/Kolkata")

    current_time = datetime.now(india_tz)

    return current_time.hour

In [5]:
# Time Range Checker Function
def is_time_between(start_hour, end_hour):

    current_hour = get_ist_hour()

    return start_hour <= current_hour < end_hour

### Number Formatter Function

In [6]:
# Human Readable Number Formatter
def human_format(num):
    if num >= 1e12:
        return f"{num/1e12:.1f}T"

    elif num >= 1e9:
        return f"{num/1e9:.1f}B"

    elif num >= 1e6:
        return f"{num/1e6:.1f}M"

    elif num >= 1e3:
        return f"{num/1e3:.1f}K"

    return str(num)

In [ ]:
# Validation of human_format function
print(human_format(1500))
print(human_format(2500000))
print(human_format(7000000000))

1.5K
2.5M
7.0B

## App Name Validation Function

In [ ]:
# Check App Name Length
def valid_app_length(app_name):

    return len(str(app_name)) <= 30

In [9]:
print(valid_app_length("Instagram"))
print(valid_app_length("This is a very very long app name"))

True
False

In [10]:
# Check If App Name Contains Letter "S"
def contains_s(app_name):

    return "s" in str(app_name).lower()

In [11]:
print(contains_s("WhatsApp"))
print(contains_s("Telegram"))

True
False

In [12]:
# Check If App Starts with X/Y/Z
def starts_with_xyz(app_name):

    app_name = str(app_name).lower()

    return app_name.startswith(
        ("x", "y", "z")
    )

In [13]:
print(starts_with_xyz("Xender"))
print(starts_with_xyz("YouTube"))
print(starts_with_xyz("Instagram"))

True
True
False

In [14]:
# Check If App Name Contains Numbers
def contains_number(app_name):

    return bool(
        re.search(r"\d", str(app_name))
    )

In [15]:
print(contains_number("PUBG"))
print(contains_number("PUBG123"))

False
True

## Task-wise Filtered Data Preparation

### Task-1

In [38]:
# Filter January Apps
task1_df = app_data[
    app_data["Update_Month_Name"] == "January"
]

In [39]:
# Filter Rating > 4
task1_df = task1_df[
    task1_df["Rating"] > 4.0
]

In [40]:
# Filter Size > 10 MB
task1_df = task1_df[
    task1_df["Size"] > 10
]

In [41]:
# Group by Category
task1_grouped = (
    task1_df.groupby("Category")
    .agg({
        "Rating": "mean",
        "Reviews": "sum",
        "Installs": "sum"
    })
    .reset_index()
)

In [42]:
# Sort by Installs
task1_grouped = (
    task1_grouped
    .sort_values(
        by="Installs",
        ascending=False
    )
)

In [43]:
# Keep Top 10 Categories
task1_grouped = task1_grouped.head(10)

In [44]:
# Preview Dataset
task1_grouped

            Category    Rating  Reviews   Installs
22            SPORTS  4.400000  1988557  120621000
11              GAME  4.342857  2209062  108691000
8             FAMILY  4.432558  3056570  108595820
23             TOOLS  4.285714   331560   72010000
17   PERSONALIZATION  4.475000   155996   15060000
19      PRODUCTIVITY  4.440000   221779   11610000
3      COMMUNICATION  4.300000   367412   11501000
6      ENTERTAINMENT  4.350000   745832   11000000
18       PHOTOGRAPHY  4.300000   542561   10000000
24  TRAVEL_AND_LOCAL  4.100000      974    1001000

In [45]:
task1_grouped.to_csv("../Data/Task_wise_dataset/task1_grouped.csv",index=False)